l_english:
 SETTING_HEADER:0 "Ustawienia"
 AI_SETTINGS:0 "Ustawienia SI"
 AI_SETTING0:0 "Zezwalaj na wojny"
 AI_SETTING1:0 "Odpowiadaj na wezwania do wojny"
 AI_SETTING2:0 "Utrzymuj traktaty"
 AI_SETTING3:0 "Operuj budżetem"
 AI_SETTING4:0 "Operuj handlem"
 AI_SETTING5:0 "Przydzielaj dowódców"
 AI_SETTING6:0 "Przydzielaj stanowiska"
 AI_SETTING7:0 "Podejmuj decyzje"
 AI_SETTING8:0 "Szukaj szybkiego pokoju"
 AI_SETTING9:0 "Kupuj wynalazki"
 AI_SETTING10:0 "Zezwalaj na rozwiązywanie jednostek"
 AI_SETTING11:0 "Kupuj tradycje wojskowe"
 AI_SETTING12:0 "Zmieniaj polityki gubernatora"
 AI_SETTING13:0 "Wznoś budowle"
 AI_SETTING14:0 "Zezwalaj na burzenie budowli"
 AI_SETTING_TT0:0 "Zezwól lub zabroń SI rozpoczynać nowe wojny."
 AI_SETTING_TT1:0 "Jeśli odznaczone, sojusznik wzywający nasz kraj do wojny zostanie automatycznie odrzucony."
 AI_SETTING_TT2:0 "Jeśli zaznaczone, SI nie wejdzie w nowe umowy dyplomatyczne oraz, jeśli to możliwe, nie złamie istniejących."
 AI_SETTING_TT3:0 "Zezwól lub zabroń SI zmieniać politykę gospodarczą."
 AI_SETTING_TT4:0 "Zezwól lub zabroń SI zmieniać szlaki handlowe."
 AI_SETTING_TT5:0 "Zezwól lub zabroń SI przypisywać nowych dowódców lub cofać przypisania istniejącym."
 AI_SETTING_TT6:0 "Zezwól lub zabroń SI ponownie przydzielać stanowiska postaciom."
 AI_SETTING_TT7:0 "Zezwól lub zabroń SI podejmować decyzje."
 AI_SETTING_TT8:0 "Jeśli zaznaczone, SI będzie próbować wyjść z wojen tak szybko, jak to możliwe, za wszelką cenę."
 AI_SETTING_TT9:0 "Zezwól lub zabroń SI kupować wynalazki."
 AI_SETTING_TT10:0 "Zezwól lub zabroń SI rozwiązywać jednostki, gdy stwierdzi, że ma to więcej niż ekonomiczne uzasadnienie."
 AI_SETTING_TT11:0 "Zezwól lub zabroń SI kupować tradycje wojskowe."
 AI_SETTING_TT12:0 "Zezwól lub zabroń SI zmieniać polityki gubernatora."
 AI_SETTING_TT13:0 "Zezwól lub zabroń SI wznosić budowle."
 AI_SETTING_TT14:0 "Zezwól lub zabroń SI burzyć budowle (jeśli uzna, że może zbudować coś lepszego na ich miejscu) lub forty (jeśli gospodarka jest nadwyrężona)."
 difficulty_very_easy_tooltip:0 "Poziom trudności: #Y Bardzo łatwy#!\n\nJest to najłatwiejsze ustawienie do gry. Ludzcy gracze otrzymają znaczne bonusy, a wszystkie kraje SI otrzymają kary.\nSI będzie również grać mniej agresywnie przeciwko ludzkiemu graczowi.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_easy_tooltip:0 "Poziom trudności: #Y Łatwy#!\n\nTe ustawienie zapewnią ci bardziej odprężające i łatwiejsze doznania. Ludzcy gracze otrzymają pomoc w postaci bonusów.\nSI będzie grać mniej agresywnie przeciwko ludzkiemu graczowi niż na normalnym poziomie trudności lub wyższym.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_normal_tooltip:0 "Poziom trudności: #Y Normalny#!\n\nTo ustawienie zapewni zrównoważone doświadczenie, bez premii dla ludzkich graczy lub SI.\nKraje SI będą traktować ludzi i inne kraje SI w ten sam sposób.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_hard_tooltip:0 "Poziom trudności: #Y Trudny#!\n\nTo ustawienie jest ustawieniem dla bardziej doświadczonych graczy.\nKraje SI otrzymają bonusy, których nie otrzymają gracze i będą bardziej agresywne.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_very_hard_tooltip:0 "Poziom trudności: #Y Bardzo trudny#!\n\nJest to najtrudniejsze ustawienie do gry. SI otrzyma znaczące bonusy, podczas gdy ludzcy gracze nie otrzymają żadnego.\nKraje SI będą bardziej agresywne.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 DIFFICULTY_TOOLTIP:0 "Poziom trudności:\nPoziom trudności pozwala kontrolować, jak trudna będzie gra, zmieniając zachowanie SI i wzmacniając kraje."
 IRONMAN_TOOLTIP:0 "#Y Ironman Mode#!:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
 IRONMAN_DISABLED_NOT_SIGNED_TOOLTIP:0 "Please sign in with your Paradox account \nto play with the #Y Ironman mode#! enabled:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
 IRONMAN_DISABLED_MP_TOOLTIP:0 "#Y Ironman mode#! is not available in Multiplayer mode:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
