l_english:
 SETTING_HINTS:0 "Podpowiedzi"
 SETTING_LAST_HOST:0 "Ostatni host"
 SETTING_LAST_PLAYER:0 "Ostatni gracz"
 SETTING_DIFFICULTY:0 "Poziom trudności"
 SETTING_AUTOSAVE:0 "Częstotliwość autozapisu"
 SETTING_DEBUG_SAVES:0 "Liczba zapisów w trybie debug"
 SETTING_WINDOW_MOVE_TIME:0 "Czas ruchu okna"
 SETTING_RADIAL_STAY_TIME:0 "Czas promienistego zastoju"
 SETTING_CAMERA_FACE_NORTH:0 "Zwrot kamery ku północy"
 SETTING_AUTOSAVE_TO_CLOUD:0 "Autozapis w chmurze"
 SETTING_DISABLED_ALERTS:0 "Wyłączone powiadomienia"
 SETTING_DISABLED_HINTS:0 "Wyłączone podpowiedzi"
 SETTING_FOCUS_ON_COMBAT:0 "Skupienie na bitwie"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP:0 "Decyduje czy prędkość gry powinna zwolnić podczas obserwacji bitwy."
 SETTING_PROVINCE_NAMES:0 "Nazwy prowincji"
 SETTING_MAX_TICKS_AHEAD:0 "Maksimum tyknięć do przodu"
 MAPNAME_MODE_ALWAYS_ON:0 "Zawsze włączone"
 MAPNAME_MODE_ALWAYS_OFF:0 "Zawsze wyłączone"
 MAPNAME_MODE_MOUSE_OVER:0 "Najechanie myszki"
 MAPNAME_MODE_DEFAULT:0 "Domyślny"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN:0 "Wypełnienie nieprzekraczalnego terenu"
 SETTING_PAUSE_ON_EVENTS:0 "Pauzuj przy wydarzeniach"
 SETTING_ADVICE:0 "Porady dot. ostrzeżeń"
 SETTING_ADVICE_TOOLTIP:0 "Określa, czy będą wyświetlane porady i podświetlenia po kliknięciu ikony ostrzeżenia (powiadomienia)"
 SETTING_DRAW_TERRAIN:0 "Wyświetlanie terenu"
 SETTING_DRAW_WATER:0 "Wyświetlanie wody"
 SETTING_DRAW_BORDERS:0 "Wyświetlanie granic"
 SETTING_DRAW_TREES:0 "Wyświetlanie drzew"
 SETTING_DRAW_RIVERS:0 "Wyświetlanie rzek"
 SETTING_DRAW_POSTFX:0 "Wyświetlanie postfx"
 SETTING_DRAW_SKY:0 "Wyświetlanie nieba"
 SETTING_DRAW_BLOOM:0 "Wyświetlanie bloomu"
 SETTING_DRAW_TOOLTIPS:0 "Wyświetlanie etykiet"
 SETTING_DRAW_CITYSPRAWL:0 "Wyświetlanie granic miasta"
 SETTING_DRAW_SHADOWS:0 "Wyświetlanie cieni"
 SETTING_OUTLINER_SHOW_OUTLINER:0 "Pokaż przybornik"
 SETTING_OUTLINER_PLAYER_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_PLAYER_NAVIES:0 "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_NAVIES:0 "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_PROVINCIAL_ARMIES:0 "Pokaż armie gracza"
 SETTING_OUTLINER_COMBATS:0 "Pokaż bitwy"
 SETTING_OUTLINER_SIEGES_OUR:0 "Pokaż nasze oblężenia"
 SETTING_OUTLINER_SIEGES_HOSTILE:0 "Pokaż wrogie oblężenia"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS:0 "Pokaż nielojalne postacie"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS:0 "Pokaż wznoszone budowle"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY:0 "Pokaż militarne konstrukcje"
 SETTING_OUTLINER_PROVINCEMODIFIER:0 "Pokaż ulepszenia terytorium"
 SETTING_OUTLINER_ACTIVE_WARS:0 "Pokaż obecne wojny"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY:0 "Pokaż aktywną dyplomację"
 SETTING_OUTLINER_HUMAN_PLAYERS:0 "Pokaż graczy"
