l_english:
 SETTING_VALUE_NONE:0 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:0 "$VALUE$ sekund"
 SETTING_RENDERER:0 "Renderowanie"
 SETTING_VSYNC:0 "Synchronizacja pionowa"
 SETTING_VSYNC_TOOLTIP:0 "#bold $SETTING_VSYNC$\n#!Sprawia, że gra generuje taką ilość klatek na sekundę, jaką jest w stanie wyświetlić twój monitor, co zmniejsza efekt rozrywania obrazu.\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_MULTI_SAMPLING:0 "Antyaliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:0 "#bold $SETTING_MULTI_SAMPLING$\n#!Korzystanie z wielopróbkowego antyaliasingu (MSAA) wygładzi krawędzie obrazów.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_ANTI_ALIASING:0 "Antyaliasing"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Użycie antyaliasingu sprawi, że krawędzie obrazów będą gładsze.\n\nFXAA jest rekomendowane."
 OPTION_ANTI_ALIASING_DISABLED:0 "Wyłączony"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Filtrowanie tekstur"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:0 "#bold $SETTING_ANISOTROPIC_FILTERING$\n#!Zastosowanie filtrowania anizotropowego poprawi wygląd teksturowanych powierzchni.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_FULLSCREEN_RESOLUTION:0 "Rozdzielczość"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:0 "#bold $SETTING_FULLSCREEN_RESOLUTION$\n#!Kontroluje jakość obrazu gry.\n\nNiższe rozdzielczości mogą zwiększyć wydajność."
 SETTING_WINDOWED_RESOLUTION:0 "Rozdzielczość w oknie"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Rozdzielczość gry. Wyższa rozdzielczość jest bardziej wymagająca sprzętowo."
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:0 "#bold $SETTING_DISPLAY$\n#!Jeśli twój komputer ma wiele monitorów, wybierz ten, który będzie wykorzystywany przez grę."
 SETTING_GRAPHICS_DEVICE:0 "Karta graficzna"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:0 "#bold $SETTING_GRAPHICS_DEVICE$\n#!Wybierz, która karta graficzna będzie używana w grze.\n\nKorzystanie ze zintegrowanej karty graficznej lub renderowania programowego może obniżyć wydajność."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Jakość cieni"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:0 "#bold $SETTING_SHADOW_MAP_RESOLUTION$\n#!Określa rozdzielczość map cieni, które są renderowane, jeśli cienie są włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_DISPLAY_MODE:0 "Tryb wyświetlania"
 SETTING_DISPLAY_MODE_TOOLTIP:0 "#T $SETTING_DISPLAY_MODE$\n#!Określa, jak gra jest wyświetlana na twoim ekranie"
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Jakość poziomu szczegółów siatki"
 SETTING_MESH_LOD_FADE:0 "Zanikanie poziomu szczegółów siatki"
 SETTING_TERRAIN_SMOOTHING:0 "Wygładzanie terenu"
 OPTION_FULLSCREEN:0 "Pełny ekran"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Wyświetla grę z użyciem całego ekranu. Ustawienie rozdzielczości zmienia ostrość obrazu."
 OPTION_WINDOWED:0 "W oknie"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Wyświetla grę w oknie. Ustawienie rozdzielczości zmienia wielkość okna."
 OPTION_DISABLED:0 "Wyłączone"
 OPTION_OFF:0 "Wyłączone"
 OPTION_LOW:0 "Niskie"
 OPTION_MEDIUM:0 "Średnie"
 OPTION_HIGH:0 "Wysokie"
 OPTION_ULTRA:0 "Ultra"
 OPTION_CUSTOM:0 "Własne"
 OPTION_DEFAULT:0 "Domyślne"
 SETTINGS_CATEGORY_UI:0 "Interfejs"
 SETTINGS_CATEGORY_GAME:0 "Gra"
 SETTING_TEXTURE_QUALITY:0 "Jakość tekstur"
 SETTING_TEXTURE_QUALITY_TOOLTIP:0 "#T $SETTING_TEXTURE_QUALITY$#!\nOkreśla rozdzielczość załadowanych tekstur.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_QUALITY:0 "Predefiniowane ustawienia jakości"
 SETTING_SFX:0 "Efekty specjalne"
 SETTING_UI:0 "Interfejs"
 SETTING_QUALITY_TOOLTIP:0 "#T $SETTING_QUALITY$\n#!Wybierz jeden z poniższych wariantów ustawień zaawansowanych opcji graficznych.\n\nUstawienie niskich ustawień predefiniowanych zwiększy wydajność."
 SETTING_BLOOM_TOOLTIP:0 "#T $SETTING_BLOOM$\n#!Włącza efekt "bloom", w którym bardzo jasne światła rozlewają się na inne części obrazu\n\nWyłączenie tej opcji może zwiększyć wydajność."
 SETTING_REFRACTION_TOOLTIP:0 "Określa, czy refrakcje pojawiają się na wodzie, czy nie."
 SETTING_REFRACTION_QUALITY_TOOLTIP:0 "#T $SETTING_REFRACTION_QUALITY$#!\nKontroluje jakość refrakcji wody, jeśli są one włączone.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "#T $SETTING_MAPOBJECT_QUALITY$#!\nOkreśla najwyższy poziom jakości obiektów mapy (takich jak budynki).\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_BIAS_TOOLTIP:0 "#T $SETTING_MESH_LOD_BIAS$#!\nOkreśla jakość LODów (poziomów szczegółowości) na obiektach mapy, takich jak modele jednostek.\n\nNiższe ustawienia mogą zwiększyć wydajność."
 SETTING_MESH_LOD_FADE_TOOLTIP:0 "#T $SETTING_MESH_LOD_FADE$\n#!Po włączeniu modele 3D płynnie przechodzą między różnymi poziomami szczegółowości (LOD) podczas przybliżania lub oddalania.\n\nWyłączenie może zwiększyć wydajność."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Określa sposób wyświetlania nazw miast i prowincji na mapie."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Określa, czy nieprzekraczalny teren znajduje się w granicach kraju na mapie."
 SETTING_LANGUAGE_TOOLTIP:0 "#T $SETTING_LANGUAGE$#!\nOkreśla język interfejsu użytkownika."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Twój adres e-mail konta Paradox"
 SETTING_FRAMERATE_CAP:0 "Maksymalna liczba FPS"
 SETTING_FRAMERATE_CAP_TOOLTIP:0 "#T $SETTING_FRAMERATE_CAP$#!\nMaksymalna liczba FPS (frames per second = klatek na sekundę), które gra będzie renderować.\n\nNiższe ustawienia mogą zmniejszyć zużycie prądu."
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 SETTING_ANIMATION_SPEED:0 "Prędkość animacji"
 SETTING_GUI_SCALING:0 "Skalowanie GUI"
 SETTING_GUI_SCALING_TOOLTIP:0 "#T $SETTING_GUI_SCALING$\n#!Kontroluje skalę całego interfejsu użytkownika. Przydatne przy wyższych rozdzielczości ekranu.\n\nUstawienie zbyt dużej wartości spowoduje, że interfejs nie będzie poprawnie pasować do ekranu!#!"
 SETTING_MOUSE_PANNING:0 "Przewijanie krawędzi ekranu"
 SETTING_MOUSE_PANNING_TOOLTIP:0 "#T $SETTING_MOUSE_PANNING$\n#!Określa, czy kamerę można przesuwać, przesuwając mysz do krawędzi ekranu."
 SETTING_SCROLL_SPEED:0 "Prędkość przewijania"
 SETTING_CAMERA_ROTATION_SPEED:0 "Prędkość obrotu kamery"
 SETTING_ZOOM_SPEED:0 "Prędkość skalowania"
 SETTING_INPUT_DEVICE:0 "Urządzenie wejściowe"
 SETTING_EDITOR:0 "Edytor"
 SETTING_EDITOR_POSTFIX:0 "Edytor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Polecenie otwarcia edytora"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "Wyświetlenie dziennika komend"
 SETTING_GRACEFUL_EXIT:0 "Zgrabne wyjście"
 SETTING_LANGUAGE:0 "Język"
 MOUSE_AND_KEYBOARD:0 "Mysz i klawiatura"
 GAMEPAD:0 "Kontroler"
 SETTING_MULTISAMPLING_DISABLED:0 "Wyłączone"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Wyłączone"
 SETTING_CAMERA_TILT:0 "Pochylenie kamery"
 SETTING_CAMERA_STRATEGY:0 "Rodzaj kamery"
 SETTING_CENTERED_ZOOM_IN:0 "Centrowane powiększenie"
 SETTING_CAMERA_SPEED:0 "Prędkość kamery"
 CAMERA_TABLETOP:0 "Płaska"
 CAMERA_FPS:0 "Pierwszoosobowa"
 CAMERA_WASD:0 "Styl WASD"
 SETTING_Music:0 "Muzyka"
 SETTING_Ambient:0 "Otoczenie"
 SETTING_Effects:0 "Efekty"
 SETTING_Master:0 "Ogólna"
 SETTING_Master_TOOLTIP:0 "#T Głośność ogólna\n#!Kontroluje głośność wszystkich dźwięków w grze."
 SETTING_Music_TOOLTIP:0 "#T Głośność muzyki\n#!Kontroluje głośność muzyki w tle."
 SETTING_Ambient_TOOLTIP:0 "#T Głośność otoczenia\n#!Kontroluje głośność otoczenia."
 SETTING_SFX_TOOLTIP:0 "#T Głośność efektów specjalnych\n#!Kontroluje głośność efektów dźwiękowych, takich jak bitwa."
 SETTING_UI_TOOLTIP:0 "#T Głośność interfejsu\n#!Kontroluje głośność interfejsu użytkownika."
 SETTING_AUDIO_DEBUG_LOG_LEVEL:0 "Poziom dziennika debugowania"
 SETTING_AUTOSAVE_TOOLTIP:0 "#T $SETTING_AUTOSAVE$\n#!Kontroluje częstotliwość automatycznego zapisywania gry."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Określa, czy autozapis ma być przechowywany w chmurze."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Określa, czy kamera zawsze będzie skierowana na północ."
 NO_AUTOSAVE:0 "Brak autozapisu"
