l_english:
 SETTING_HEADER: "Ustawienia"
 AI_SETTINGS: "Ustawienia SI"
 AI_SETTING0: "Zezwalaj na wojny"
 AI_SETTING1: "Odpowiadaj na wezwania do wojny"
 AI_SETTING2: "Utrzymuj traktaty"
 AI_SETTING3: "Operuj budżetem"
 AI_SETTING4: "Operuj handlem"
 AI_SETTING5: "Przydzielaj dowódców"
 AI_SETTING6: "Przydzielaj stanowiska"
 AI_SETTING7: "Podejmuj decyzje"
 AI_SETTING8: "Szukaj szybkiego pokoju"
 AI_SETTING9: "Kupuj wynalazki"
 AI_SETTING10: "Zezwalaj na rozwiązywanie jednostek"
 AI_SETTING11: "Kupuj tradycje wojskowe"
 AI_SETTING12: "Zmieniaj polityki gubernatora"
 AI_SETTING13: "Wznoś budowle"
 AI_SETTING14: "Zezwalaj na burzenie budowli"
 AI_SETTING_TT0: "Zezwól lub zabroń SI rozpoczynać nowe wojny."
 AI_SETTING_TT1: "Jeśli odznaczone, sojusznik wzywający nasz kraj do wojny zostanie automatycznie odrzucony."
 AI_SETTING_TT2: "Jeśli zaznaczone, SI nie wejdzie w nowe umowy dyplomatyczne oraz, jeśli to możliwe, nie złamie istniejących."
 AI_SETTING_TT3: "Zezwól lub zabroń SI zmieniać politykę gospodarczą."
 AI_SETTING_TT4: "Zezwól lub zabroń SI zmieniać szlaki handlowe."
 AI_SETTING_TT5: "Zezwól lub zabroń SI przypisywać nowych dowódców lub cofać przypisania istniejącym."
 AI_SETTING_TT6: "Zezwól lub zabroń SI ponownie przydzielać stanowiska postaciom."
 AI_SETTING_TT7: "Zezwól lub zabroń SI podejmować decyzje."
 AI_SETTING_TT8: "Jeśli zaznaczone, SI będzie próbować wyjść z wojen tak szybko, jak to możliwe, za wszelką cenę."
 AI_SETTING_TT9: "Zezwól lub zabroń SI kupować wynalazki."
 AI_SETTING_TT10: "Zezwól lub zabroń SI rozwiązywać jednostki, gdy stwierdzi, że ma to więcej niż ekonomiczne uzasadnienie."
 AI_SETTING_TT11: "Zezwól lub zabroń SI kupować tradycje wojskowe."
 AI_SETTING_TT12: "Zezwól lub zabroń SI zmieniać polityki gubernatora."
 AI_SETTING_TT13: "Zezwól lub zabroń SI wznosić budowle."
 AI_SETTING_TT14: "Zezwól lub zabroń SI burzyć budowle (jeśli uzna, że może zbudować coś lepszego na ich miejscu) lub forty (jeśli gospodarka jest nadwyrężona)."
 difficulty_very_easy_tooltip: "Poziom trudności: #Y Bardzo łatwy#!\n\nJest to najłatwiejsze ustawienie do gry. Ludzcy gracze otrzymają znaczne bonusy, a wszystkie kraje SI otrzymają kary.\nSI będzie również grać mniej agresywnie przeciwko ludzkiemu graczowi.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_easy_tooltip: "Poziom trudności: #Y Łatwy#!\n\nTe ustawienie zapewnią ci bardziej odprężające i łatwiejsze doznania. Ludzcy gracze otrzymają pomoc w postaci bonusów.\nSI będzie grać mniej agresywnie przeciwko ludzkiemu graczowi niż na normalnym poziomie trudności lub wyższym.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_normal_tooltip: "Poziom trudności: #Y Normalny#!\n\nTo ustawienie zapewni zrównoważone doświadczenie, bez premii dla ludzkich graczy lub SI.\nKraje SI będą traktować ludzi i inne kraje SI w ten sam sposób.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_hard_tooltip: "Poziom trudności: #Y Trudny#!\n\nTo ustawienie jest ustawieniem dla bardziej doświadczonych graczy.\nKraje SI otrzymają bonusy, których nie otrzymają gracze i będą bardziej agresywne.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 difficulty_very_hard_tooltip: "Poziom trudności: #Y Bardzo trudny#!\n\nJest to najtrudniejsze ustawienie do gry. SI otrzyma znaczące bonusy, podczas gdy ludzcy gracze nie otrzymają żadnego.\nKraje SI będą bardziej agresywne.\n\n#T Modyfikatory gracza:#!\n$PLAYER_MODIFIERS$\n#T Modyfikatory SI:#!\n$AI_MODIFIERS$"
 DIFFICULTY_TOOLTIP: "Poziom trudności:\nPoziom trudności pozwala kontrolować, jak trudna będzie gra, zmieniając zachowanie SI i wzmacniając kraje."
 IRONMAN_TOOLTIP: "#Y Tryb Ironman#!:\n\nTryb gry dla bardziej wymagających.\n- #T Włącza osiągnięcia, jeśli nie są aktywne żadne mody#!.\n- Ogranicza liczbę plików zapisu gry do jednego.\n- Nieopcjonalny i częsty automatyczny zapis.\n- Nie można używać konsoli w grze.\n- Nie można przełączać krajów."
 IRONMAN_DISABLED_NOT_SIGNED_TOOLTIP: "Zaloguj się za pomocą konta Paradox \naby grać z włączonym #Y trybem Ironman#!:\n\nTryb gry dla bardziej wymagających.\n- #T Włącza osiągnięcia, jeśli nie są aktywne żadne mody#!.\n- Ogranicza liczbę plików zapisu gry do jednego.\n- Nieopcjonalny i częsty automatyczny zapis.\n- Nie można używać konsoli w grze.\n- Nie można przełączać krajów."
 IRONMAN_DISABLED_MP_TOOLTIP: "#Y Tryb Ironman#! nie jest dostępny w trybie wieloosobowym:\n\nTryb gry dla bardziej wymagających.\n- #T Włącza osiągnięcia, jeśli nie są aktywne żadne mody#!.\n- Ogranicza liczbę plików zapisu gry do jednego.\n- Nieopcjonalny i częsty automatyczny zapis.\n- Nie można używać konsoli w grze.\n- Nie można przełączać krajów."
 IRONMAN_MODS_ENABLED_TOOLTIP: "#Y Tryb Ironman#!:\n \n#N (Uruchomienie trybu Ironman z aktywnymi modami wyłączy osiągnięcia)#!\n\nTryb gry dla bardziej wymagających.\n- #T Włącza osiągnięcia, jeśli nie są aktywne żadne mody#!.\n- Ogranicza liczbę plików zapisu gry do jednego.\n- Nieopcjonalny i częsty automatyczny zapis.\n- Nie można używać konsoli w grze.\n- Nie można przełączać krajów."
