l_english:
 SETTING_HEADER: ""
 AI_SETTINGS: ""
 AI_SETTING0: ""
 AI_SETTING1: ""
 AI_SETTING2: ""
 AI_SETTING3: ""
 AI_SETTING4: ""
 AI_SETTING5: ""
 AI_SETTING6: ""
 AI_SETTING7: ""
 AI_SETTING8: ""
 AI_SETTING9: ""
 AI_SETTING10: ""
 AI_SETTING11: ""
 AI_SETTING12: ""
 AI_SETTING13: ""
 AI_SETTING14: ""
 AI_SETTING_TT0: ""
 AI_SETTING_TT1: ""
 AI_SETTING_TT2: ""
 AI_SETTING_TT3: ""
 AI_SETTING_TT4: ""
 AI_SETTING_TT5: ""
 AI_SETTING_TT6: ""
 AI_SETTING_TT7: ""
 AI_SETTING_TT8: ""
 AI_SETTING_TT9: ""
 AI_SETTING_TT10: ""
 AI_SETTING_TT11: ""
 AI_SETTING_TT12: ""
 AI_SETTING_TT13: ""
 AI_SETTING_TT14: ""
 difficulty_very_easy_tooltip: ""
 difficulty_easy_tooltip: ""
 difficulty_normal_tooltip: ""
 difficulty_hard_tooltip: ""
 difficulty_very_hard_tooltip: ""
 DIFFICULTY_TOOLTIP: ""
 IRONMAN_TOOLTIP: ""
 IRONMAN_DISABLED_NOT_SIGNED_TOOLTIP: ""
 IRONMAN_DISABLED_MP_TOOLTIP: ""
 IRONMAN_MODS_ENABLED_TOOLTIP: ""
