l_english:
 SETTING_HINTS: ""
 SETTING_LAST_HOST: ""
 SETTING_LAST_PLAYER: ""
 SETTING_DIFFICULTY: ""
 SETTING_AUTOSAVE: ""
 SETTING_DEBUG_SAVES: ""
 SETTING_WINDOW_MOVE_TIME: ""
 SETTING_RADIAL_STAY_TIME: ""
 SETTING_CAMERA_FACE_NORTH: ""
 SETTING_AUTOSAVE_TO_CLOUD: ""
 SETTING_DISABLED_ALERTS: ""
 SETTING_DISABLED_HINTS: ""
 SETTING_FOCUS_ON_COMBAT: ""
 SETTING_FOCUS_ON_COMBAT_TOOLTIP: ""
 SETTING_PROVINCE_NAMES: ""
 SETTING_MAX_TICKS_AHEAD: ""
 MAPNAME_MODE_ALWAYS_ON: ""
 MAPNAME_MODE_ALWAYS_OFF: ""
 MAPNAME_MODE_MOUSE_OVER: ""
 MAPNAME_MODE_DEFAULT: ""
 SETTING_FILL_IN_IMPASSABLE_TERRAIN: ""
 SETTING_PAUSE_ON_EVENTS: ""
 SETTING_ADVICE: ""
 SETTING_ADVICE_TOOLTIP: ""
 SETTING_DRAW_TERRAIN: ""
 SETTING_DRAW_WATER: ""
 SETTING_DRAW_BORDERS: ""
 SETTING_DRAW_TREES: ""
 SETTING_DRAW_RIVERS: ""
 SETTING_DRAW_POSTFX: ""
 SETTING_DRAW_SKY: ""
 SETTING_DRAW_BLOOM: ""
 SETTING_DRAW_TOOLTIPS: ""
 SETTING_DRAW_CITYSPRAWL: ""
 SETTING_DRAW_SHADOWS: ""
 SETTING_OUTLINER_SHOW_OUTLINER: ""
 SETTING_OUTLINER_PLAYER_ARMIES: ""
 SETTING_OUTLINER_PLAYER_NAVIES: ""
 SETTING_OUTLINER_AUTOMATED_NAVIES: ""
 SETTING_OUTLINER_AUTOMATED_ARMIES: ""
 SETTING_OUTLINER_PROVINCIAL_ARMIES: ""
 SETTING_OUTLINER_COMBATS: ""
 SETTING_OUTLINER_SIEGES_OUR: ""
 SETTING_OUTLINER_SIEGES_HOSTILE: ""
 SETTING_OUTLINER_DISLOYAL_CHARACTERS: ""
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS: ""
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY: ""
 SETTING_OUTLINER_PROVINCEMODIFIER: ""
 SETTING_OUTLINER_ACTIVE_WARS: ""
 SETTING_OUTLINER_ACTIVE_DIPLOMACY: ""
 SETTING_OUTLINER_HUMAN_PLAYERS: ""
