l_english:
 SETTING_HINTS: "Podpowiedzi"
 SETTING_LAST_HOST: "Ostatni host"
 SETTING_LAST_PLAYER: "Ostatni gracz"
 SETTING_DIFFICULTY: "Poziom trudności"
 SETTING_AUTOSAVE: "Częstotliwość autozapisu"
 SETTING_DEBUG_SAVES: "Liczba zapisów w trybie debug"
 SETTING_WINDOW_MOVE_TIME: "Czas ruchu okna"
 SETTING_RADIAL_STAY_TIME: "Czas promienistego zastoju"
 SETTING_CAMERA_FACE_NORTH: "Zwrot kamery ku północy"
 SETTING_AUTOSAVE_TO_CLOUD: "Autozapis w chmurze"
 SETTING_DISABLED_ALERTS: "Wyłączone powiadomienia"
 SETTING_DISABLED_HINTS: "Wyłączone podpowiedzi"
 SETTING_FOCUS_ON_COMBAT: "Skupienie na bitwie"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP: "Decyduje czy prędkość gry powinna zwolnić podczas obserwacji bitwy."
 SETTING_PROVINCE_NAMES: "Nazwy prowincji"
 SETTING_MAX_TICKS_AHEAD: "Maksimum tyknięć do przodu"
 MAPNAME_MODE_ALWAYS_ON: "Zawsze włączone"
 MAPNAME_MODE_ALWAYS_OFF: "Zawsze wyłączone"
 MAPNAME_MODE_MOUSE_OVER: "Najechanie myszki"
 MAPNAME_MODE_DEFAULT: "Domyślny"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN: "Wypełnienie nieprzekraczalnego terenu"
 SETTING_PAUSE_ON_EVENTS: "Pauzuj przy wydarzeniach"
 SETTING_ADVICE: "Porady dot. ostrzeżeń"
 SETTING_ADVICE_TOOLTIP: "Określa, czy będą wyświetlane porady i podświetlenia po kliknięciu ikony ostrzeżenia (powiadomienia)"
 SETTING_DRAW_TERRAIN: "Wyświetlanie terenu"
 SETTING_DRAW_WATER: "Wyświetlanie wody"
 SETTING_DRAW_BORDERS: "Wyświetlanie granic"
 SETTING_DRAW_TREES: "Wyświetlanie drzew"
 SETTING_DRAW_RIVERS: "Wyświetlanie rzek"
 SETTING_DRAW_POSTFX: "Wyświetlanie postfx"
 SETTING_DRAW_SKY: "Wyświetlanie nieba"
 SETTING_DRAW_BLOOM: "Wyświetlanie bloomu"
 SETTING_DRAW_TOOLTIPS: "Wyświetlanie etykiet"
 SETTING_DRAW_CITYSPRAWL: "Wyświetlanie granic miasta"
 SETTING_DRAW_SHADOWS: "Wyświetlanie cieni"
 SETTING_OUTLINER_SHOW_OUTLINER: "Pokaż przybornik"
 SETTING_OUTLINER_PLAYER_ARMIES: "Pokaż armie gracza"
 SETTING_OUTLINER_PLAYER_NAVIES: "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_NAVIES: "Pokaż floty gracza"
 SETTING_OUTLINER_AUTOMATED_ARMIES: "Pokaż armie gracza"
 SETTING_OUTLINER_PROVINCIAL_ARMIES: "Pokaż armie gracza"
 SETTING_OUTLINER_COMBATS: "Pokaż bitwy"
 SETTING_OUTLINER_SIEGES_OUR: "Pokaż nasze oblężenia"
 SETTING_OUTLINER_SIEGES_HOSTILE: "Pokaż wrogie oblężenia"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS: "Pokaż nielojalne postacie"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS: "Pokaż wznoszone budowle"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY: "Pokaż militarne konstrukcje"
 SETTING_OUTLINER_PROVINCEMODIFIER: "Pokaż ulepszenia terytorium"
 SETTING_OUTLINER_ACTIVE_WARS: "Pokaż obecne wojny"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY: "Pokaż aktywną dyplomację"
 SETTING_OUTLINER_HUMAN_PLAYERS: "Pokaż graczy"
