l_english:
 SETTING_HEADER: "Setting"
 AI_SETTINGS: "AI Settings"
 AI_SETTING0: "Allow Wars"
 AI_SETTING1: "Answer Call to Arms"
 AI_SETTING2: "Keep Treaties"
 AI_SETTING3: "Handle Budget"
 AI_SETTING4: "Handle Trade"
 AI_SETTING5: "Assign Commanders"
 AI_SETTING6: "Assign Offices"
 AI_SETTING7: "Take Decisions"
 AI_SETTING8: "Seek Fast Peace"
 AI_SETTING9: "Buy Inventions"
 AI_SETTING10: "Allow Disband Units"
 AI_SETTING11: "Buy Military Traditions"
 AI_SETTING12: "Change Governor Policies"
 AI_SETTING13: "Construct Buildings"
 AI_SETTING14: "Allow Demolish Buildings"
 AI_SETTING_TT0: "Allow or deny the AI to start new wars."
 AI_SETTING_TT1: "If unchecked, an ally calling our country to war will be automatically rejected."
 AI_SETTING_TT2: "If checked, the AI will not enter new diplomatic agrements, nor break existing ones if possible."
 AI_SETTING_TT3: "Allow or deny the AI to alter Economic policies."
 AI_SETTING_TT4: "Allow or deny the AI to alter Trade routes."
 AI_SETTING_TT5: "Allow or deny the AI to assign new commanders or unassign existing ones."
 AI_SETTING_TT6: "Allow or deny the AI to reassign office jobs to characters."
 AI_SETTING_TT7: "Allow or deny the AI to take Decisions."
 AI_SETTING_TT8: "If checked, the AI will attempt to peace out of wars as fast as possible, at any cost."
 AI_SETTING_TT9: "Allow or deny the AI to buy Inventions."
 AI_SETTING_TT10: "Allow or deny the AI to disband units when it determines it has more than economically wise."
 AI_SETTING_TT11: "Allow or deny the AI to buy Military traditions."
 AI_SETTING_TT12: "Allow or deny the AI to change governor policies."
 AI_SETTING_TT13: "Allow or deny the AI to construct buildings."
 AI_SETTING_TT14: "Allow or deny the AI to demolish a building if it thinks it can build something better in its place, or forts if its economy is strained."
 difficulty_very_easy_tooltip: "Difficulty: #Y Very Easy#!\n\nThis is the easiest setting to play the game in. Human players will be given substantial bonuses and all AI countries will suffer penalties.\nThe AI will also play less aggressively against the human player.\n\n#T Player modifiers:#!\n$PLAYER_MODIFIERS$\n#T AI modifiers:#!\n$AI_MODIFIERS$"
 difficulty_easy_tooltip: "Difficulty: #Y Easy#!\n\nThis settings will give a more relaxed and easier experience. Human players will be helped with bonuses.\nThe AI will play less aggressively against the human player than it would on normal or above.\n\n#T Player modifiers:#!\n$PLAYER_MODIFIERS$\n#T AI modifiers:#!\n$AI_MODIFIERS$"
 difficulty_normal_tooltip: "Difficulty: #Y Normal#!\n\nThis setting will give a balanced experience, with no bonuses to the human player or the AI.\nAI countries will treat Humans and other AI countries the same way.\n\n#T Player modifiers:#!\n$PLAYER_MODIFIERS$\n#T AI modifiers:#!\n$AI_MODIFIERS$"
 difficulty_hard_tooltip: "Difficulty: #Y Hard#!\n\nThis setting is a setting for more experienced players.\nAI countries will receive bonuses that human players will not and will be more aggressive.\n\n#T Player modifiers:#!\n$PLAYER_MODIFIERS$\n#T AI modifiers:#!\n$AI_MODIFIERS$"
 difficulty_very_hard_tooltip: "Difficulty: #Y Very Hard#!\n\nThis is the hardest setting to play in. The AI will be given substantial bonuses while human players get none.\nAI countries will be more aggressive.\n\n#T Player modifiers:#!\n$PLAYER_MODIFIERS$\n#T AI modifiers:#!\n$AI_MODIFIERS$"
 DIFFICULTY_TOOLTIP: "Difficulty:\nDifficulty allows you to control how hard the game will be by changing AI behavior and strengthening countries."
 IRONMAN_TOOLTIP: "#Y Ironman Mode#!:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
 IRONMAN_DISABLED_NOT_SIGNED_TOOLTIP: "Please sign in with your Paradox account \nto play with the #Y Ironman mode#! enabled:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
 IRONMAN_DISABLED_MP_TOOLTIP: "#Y Ironman mode#! is not available in Multiplayer mode:\n\nA game mode for a more challenging experience.\n- #T Enables Achievements#!.\n- Limits the number of save files per game to one.\n- Non-optional and frequent autosaving.\n- Cannot use the ingame console.\n- Cannot switch countries."
