l_english:
 SETTING_HINTS: "Hints"
 SETTING_LAST_HOST: "Last host"
 SETTING_LAST_PLAYER: "Last player"
 SETTING_DIFFICULTY: "Difficulty"
 SETTING_AUTOSAVE: "Autosave interval"
 SETTING_DEBUG_SAVES: "Number of debug saves"
 SETTING_WINDOW_MOVE_TIME: "Window move time"
 SETTING_RADIAL_STAY_TIME: "Radial stay time"
 SETTING_CAMERA_FACE_NORTH: "Camera face north"
 SETTING_AUTOSAVE_TO_CLOUD: "Autosave to cloud"
 SETTING_DISABLED_ALERTS: "Disabled alerts"
 SETTING_DISABLED_HINTS: "Disabled hints"
 SETTING_FOCUS_ON_COMBAT: "Focus on combat"
 SETTING_FOCUS_ON_COMBAT_TOOLTIP: "Determines if the game speed should be restricted when observing a combat."
 SETTING_PROVINCE_NAMES: "Province names"
 SETTING_MAX_TICKS_AHEAD: "Max ticks ahead"
 MAPNAME_MODE_ALWAYS_ON: "Always on"
 MAPNAME_MODE_ALWAYS_OFF: "Always off"
 MAPNAME_MODE_MOUSE_OVER: "Mouse over"
 MAPNAME_MODE_DEFAULT: "Default"
 SETTING_FILL_IN_IMPASSABLE_TERRAIN: "Fill in impassable terrain"
 SETTING_PAUSE_ON_EVENTS: "Pause on events"
 SETTING_ADVICE: "Advice on alert"
 SETTING_ADVICE_TOOLTIP: "Determines if advice and highlights will be shown when clicking an alert icon"
 SETTING_DRAW_TERRAIN: "Draw terrain"
 SETTING_DRAW_WATER: "Draw water"
 SETTING_DRAW_BORDERS: "Draw borders"
 SETTING_DRAW_TREES: "Draw trees"
 SETTING_DRAW_RIVERS: "Draw rivers"
 SETTING_DRAW_POSTFX: "Draw postfx"
 SETTING_DRAW_SKY: "Draw sky"
 SETTING_DRAW_BLOOM: "Draw bloom"
 SETTING_DRAW_TOOLTIPS: "Draw tooltips"
 SETTING_DRAW_CITYSPRAWL: "Draw city sprawl"
 SETTING_DRAW_SHADOWS: "Draw shadows"
 SETTING_OUTLINER_SHOW_OUTLINER: "Show outliner"
 SETTING_OUTLINER_PLAYER_ARMIES: "Show player armies"
 SETTING_OUTLINER_PLAYER_NAVIES: "Show player navies"
 SETTING_OUTLINER_AUTOMATED_NAVIES: "Show player navies"
 SETTING_OUTLINER_AUTOMATED_ARMIES: "Show player navies"
 SETTING_OUTLINER_PROVINCIAL_ARMIES: "Show player navies"
 SETTING_OUTLINER_COMBATS: "Show combats"
 SETTING_OUTLINER_SIEGES_OUR: "Show our sieges"
 SETTING_OUTLINER_SIEGES_HOSTILE: "Show hostile sieges"
 SETTING_OUTLINER_DISLOYAL_CHARACTERS: "Show disloyal characters"
 SETTING_OUTLINER_CONSTRUCTIONS_BUILDINGS: "Show building constructions"
 SETTING_OUTLINER_CONSTRUCTIONS_MILITARY: "Show military constructions"
 SETTING_OUTLINER_PROVINCEMODIFIER: "Show territory improvements"
 SETTING_OUTLINER_ACTIVE_WARS: "Show active wars"
 SETTING_OUTLINER_ACTIVE_DIPLOMACY: "Show Active Diplomacy"
 SETTING_OUTLINER_HUMAN_PLAYERS: "Show human players"
